# Generated by Django 4.0.10 on 2023-02-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titel',
            new_name='title',
        ),
    ]
